name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
    paths:
      - 'Task-1-Portfolio-Website/**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Task-1-Portfolio-Website
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./Task-1-Portfolio-Website/package-lock.json
      - name: Install & Build Portfolio
        working-directory: ./Task-1-Portfolio-Website
        run: |
          npm ci
          npm run build
      - name: Install & Build Counter App
        working-directory: ./Task-2-Counter-App
        run: |
          npm ci
          NODE_ENV=production npm run build
      - name: Combine builds
        run: |
          mkdir -p ./Task-1-Portfolio-Website/dist/counter-app
          cp -r ./Task-2-Counter-App/dist/* ./Task-1-Portfolio-Website/dist/counter-app/
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './Task-1-Portfolio-Website/dist'
      - id: deployment
        uses: actions/deploy-pages@v4
